=== RADAR-base/RADAR-REDCap-aRMT-Definitions/docs/definition-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "title": "RADAR-base definition schema for the aRMT app questionnaires",
  "description": "A definition file for the RADAR-base aRMT app describes what questions and question input types should be displayed to the user for a questionnaire. This contains an array of questions.",
  "items": {
    "type": "object",
    "description": "A single question describing the display text, question input type, and other relevant information.",
    "properties": {
      "field_name": {
        "type": "string"
      },
      "form_name": {
        "type": "string"
      },
      "section_header": {
        "type": "string"
      },
      "field_type": {
        "type": "string",
        "enum": [
          "radio",
          "checkbox",
          "healthkit",
          "range",
          "range-info",
          "slider",
          "slider-vertical",
          "info",
          "audio",
          "guided-audio",
          "timed",
          "text",
          "yesno",
          "descriptive",
          "matrix-radio",
          "launcher",
          "web",
          "notes"
        ]
      },
      "field_label": {
        "type": "string"
      },
      "select_choices_or_calculations": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string"
                },
                "label": {
                  "type": "string"
                }
              },
              "required": [
                "code",
                "label"
              ]
            }
          }
        ]
      },
      "field_note": {
        "type": "string"
      },
      "text_validation_type_or_show_slider_number": {
        "anyOf": [
          {
            "type": "string",
            "enum": [
              "date",
              "time",
              "duration",
              "date_dmy",
              "datetime_dmy",
              "number",
              "integer"
            ]
          },
          {
            "type": "string",
            "maxLength": 0
          }
        ]
      },
      "text_validation_min": {
        "type": "string"
      },
      "text_validation_max": {
        "type": "string"
      },
      "identifier": {
        "type": "string"
      },
      "branching_logic": {
        "type": "string"
      },
      "required_field": {
        "type": "string"
      },
      "custom_alignment": {
        "type": "string"
      },
      "question_number": {
        "type": "string"
      },
      "matrix_group_name": {
        "type": "string"
      },
      "matrix_ranking": {
        "type": "string"
      },
      "field_annotation": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "object"
          }
        ]
      },
      "evaluated_logic": {
        "type": "string"
      }
    },
    "required": [
      "field_name",
      "form_name",
      "section_header",
      "field_type",
      "select_choices_or_calculations",
      "field_note",
      "text_validation_type_or_show_slider_number",
      "text_validation_min",
      "text_validation_max",
      "identifier",
      "branching_logic",
      "required_field",
      "custom_alignment",
      "question_number",
      "matrix_group_name",
      "matrix_ranking",
      "field_annotation",
      "evaluated_logic"
    ]
  }
}

=== RADAR-base/RADAR-REDCap-aRMT-Definitions/questionnaires/patient_determined_disease_step/patient_determined_disease_step_armt_es.json
[
    {
        "field_name": "pdss",
        "form_name": "patient_determined_disease_step",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Which category describes your walking situation closest?",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "<B>Normal:</B> I may have some mild symptoms"
            },
            {
                "code": "\r1",
                "label": "<B>Mild Disability:</B> I have some noticeable symptoms from my MS but they are minor and have only a small effect on my lifestyle."
            },
            {
                "code": "\r2",
                "label": "<B>Moderate Disability:</B> I do not have any limitations in my walking ability. However"
            },
            {
                "code": "\r3",
                "label": "<B>Gait Disability:</B> MS does interfere with my activities"
            },
            {
                "code": "\r4",
                "label": "<B>Early Cane:</B> I use a cane or a single crutch or some other form of support (such as touching a wall or leaning on someones arm) for walking all the time or part of the time"
            },
            {
                "code": "\r5",
                "label": "<B>Late Cane:</B> To be able to walk 25 feet"
            },
            {
                "code": "\r6",
                "label": "<B>Bilateral Support:</B> To be able to walk as far as 25 feet I must have 2 canes or crutches or a walker. I may use a scooter or wheelchair for longer distances."
            },
            {
                "code": "\r7",
                "label": "<B>Wheelchair / Scooter:</B> My main form of mobility is a wheelchair. I may be able to stand and/or take one or two steps"
            },
            {
                "code": "\r8",
                "label": "<B>Bedridden:</B> Unable to sit in a wheelchair for more than one"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "Instructions: Please read the choices listed below and choose the one that best describes your own situation.\nThis scale focuses mainly on how well you walk. You might not find a description that reflects\nyour condition exactly, but please mark the one category that describes your situation the closest.",
        "evaluated_logic": ""
    }
]

=== RADAR-base/RADAR-REDCap-aRMT-Definitions/questionnaires/maam_phq8/maam_phq8_armt.json
[
    {
        "field_name": "phq_8_1",
        "form_name": "maam_phq8",
        "section_header": "Today, how much have you been bothered by any of the following problems?",
        "field_type": "radio",
        "field_label": "Little interest or pleasure in doing things",
        "select_choices_or_calculations": [
            {
                "code": "1",
                "label": "Not at all"
            },
            {
                "code": "2",
                "label": "A little bit"
            },
            {
                "code": "3",
                "label": "Moderately"
            },
            {
                "code": "4",
                "label": "Quite a bit"
            },
            {
                "code": "5",
                "label": "Extremely"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "y",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "phq_8",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "phq_8_2",
        "form_name": "maam_phq8",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Feeling down, depressed, or hopeless",
        "select_choices_or_calculations": [
            {
                "code": "1",
                "label": "Not at all"
            },
            {
                "code": "2",
                "label": "A little bit"
            },
            {
                "code": "3",
                "label": "Moderately"
            },
            {
                "code": "4",
                "label": "Quite a bit"
            },
            {
                "code": "5",
                "label": "Extremely"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "y",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "phq_8",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    }
]

=== RADAR-base/RADAR-REDCap-aRMT-Definitions/questionnaires/recurrrent_who_proxy/recurrent_who_proxy_armt.json
[
    {
        "field_name": "swqpr_date",
        "form_name": "proxy_six_weekly_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Date completed",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "date_dmy",
        "text_validation_min": "[screening_arm_1][sf_date]",
        "text_validation_max": "today",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "swqpr_header",
        "form_name": "proxy_six_weekly_questionnaire",
        "section_header": "",
        "field_type": "descriptive",
        "field_label": "<div class=\"rich-text-field-label\"><table border=\"\" width=\"100%\" cellpadding=\"15\" bgcolor=\"#F1948A\"> <tbody> <tr> <td style=\"border-style: solid; border-width: 1px;\"><center> <h5><br><strong>This form should be completed in SURVEY mode. <br><br>Please <a style=\"font-size: large;\" href=\"[survey-url:proxy_six_weekly_questionnaire]\"><strong>CLICK HERE</strong></a> to begin,<br><br></strong><strong>and then click the <span style=\"color: #800000;\">Leave without saving changes</span> button to proceed.</strong></h5> <p> </p> </center></td> </tr> </tbody> </table></div>",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "swqpr_instruction",
        "form_name": "proxy_six_weekly_questionnaire",
        "section_header": "",
        "field_type": "descriptive",
        "field_label": "Please answer the following questions about the person who you are acting as a proxy for in the RECURRENT-GB study.",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "swqpr_who_performance",
        "form_name": "proxy_six_weekly_questionnaire",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Which of the below numbers do you think best describes them at the moment:",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "Fully active (Able to carry on all pre-disease performance without restriction)"
            },
            {
                "code": "1",
                "label": "Restricted in physically strenuous activity but they can walk and are able to carry out work of a light or sedentary nature (e.g. light housework or office work)"
            },
            {
                "code": "2",
                "label": "Able to get around and capable of self-care but unable to carry out any work activities; up and about more than 50% of their waking hours"
            },
            {
                "code": "3",
                "label": "Capable of only limited self-care, confined to a bed or chair more than 50% of their waking hours"
            },
            {
                "code": "4",
                "label": "Completely disabled. Cannot carry out any self-care. Totally confined to a bed or chair."
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    }
]

=== RADAR-base/RADAR-REDCap-aRMT-Definitions/questionnaires/art_menstruation_consent/art_menstruation_consent_armt.json
[
  {
    "field_name": "initial_info",
    "form_name": "art_menstruation_consent",
    "section_header": "",
    "field_type": "info",
    "field_label": "",
    "select_choices_or_calculations": [
      {
        "code": "Help Us Understand How Menstrual Cycles Affect ADHD",
        "label": "There is accumulating evidence that ADHD and related symptoms are affected by menstrual cycles. We want to explore this in the ART-transition study to contribute to this evidence."
      }
    ],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "",
    "matrix_group_name": "",
    "matrix_ranking": "",
    "field_annotation": "",
    "evaluated_logic": ""
  },
  {
    "field_name": "initial_consent",
    "form_name": "art_menstruation_consent",
    "section_header": "",
    "field_type": "radio",
    "field_label": "Do you menstruate (i.e., do you get a period)?",
    "select_choices_or_calculations": [
      {
        "code": "1",
        "label": "Yes"
      },
      {
        "code": "0",
        "label": "No"
      },
      {
        "code": "2",
        "label": "I would prefer not to answer questions about menstruation"
      }
    ],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "",
    "matrix_group_name": "",
    "matrix_ranking": "",
    "field_annotation": "",
    "evaluated_logic": ""
  },
  {
    "field_name": "questionnaire_consent",
    "form_name": "art_menstruation_consent",
    "section_header": "",
    "field_type": "yesno",
    "field_label": "Would you be willing to answer a brief weekly question about your menstruation? ",
    "select_choices_or_calculations": "",
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "[initial_consent] = '1'",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "",
    "matrix_group_name": "",
    "matrix_ranking": "",
    "field_annotation": "",
    "evaluated_logic": "response[initial_consent] == '1'"
  },
  {
    "field_name": "more_info",
    "form_name": "art_menstruation_consent",
    "section_header": "",
    "field_type": "text",
    "field_label": "Is there anything else you would like us to know about having or not having periods/menstruating? (e.g., contraception, irregular cycles, or related health issues)",
    "select_choices_or_calculations": "",
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "[initial_consent] = '0' or [questionnaire_consent] = '1'",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "",
    "matrix_group_name": "",
    "matrix_ranking": "",
    "field_annotation": "",
    "evaluated_logic": "response[initial_consent] == '0' || response[questionnaire_consent] == '1'"
  }
]

=== RADAR-base/RADAR-REDCap-aRMT-Definitions/questionnaires/recurrent_who_proxy/recurrent_who_proxy_armt.json
[
    {
        "field_name": "swqpr_date",
        "form_name": "proxy_six_weekly_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Date completed",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "date_dmy",
        "text_validation_min": "[screening_arm_1][sf_date]",
        "text_validation_max": "today",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "swqpr_instruction",
        "form_name": "proxy_six_weekly_questionnaire",
        "section_header": "",
        "field_type": "descriptive",
        "field_label": "Please answer the following questions about the person who you are acting as a proxy for in the RECURRENT-GB study.",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "swqpr_who_performance",
        "form_name": "proxy_six_weekly_questionnaire",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Which of the below numbers do you think best describes them at the moment:",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "Fully active (Able to carry on all pre-disease performance without restriction)"
            },
            {
                "code": "1",
                "label": "Restricted in physically strenuous activity but they can walk and are able to carry out work of a light or sedentary nature (e.g. light housework or office work)"
            },
            {
                "code": "2",
                "label": "Able to get around and capable of self-care but unable to carry out any work activities; up and about more than 50% of their waking hours"
            },
            {
                "code": "3",
                "label": "Capable of only limited self-care, confined to a bed or chair more than 50% of their waking hours"
            },
            {
                "code": "4",
                "label": "Completely disabled. Cannot carry out any self-care. Totally confined to a bed or chair."
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    }
]

=== RADAR-base/RADAR-REDCap-aRMT-Definitions/questionnaires/charite-pilot/6th-month/communication_platform/communication_platform_armt_de.json
[
  {
    "field_name": "HCACCESS",
    "form_name": "communication_platform",
    "section_header": "Access to healthcare",
    "field_type": "radio",
    "field_label": "Wie sicher sind Sie, dass sie eine medizinische Fachkraft erreichen können, wenn Sie Hilfe mit Ihrem Diabetes benötigen?",
    "select_choices_or_calculations": [
      {
        "code": "1",
        "label": "Überhaupt nicht"
      },
      {
        "code": "2",
        "label": "Ein wenig"
      },
      {
        "code": "3",
        "label": "Mäßig"
      },
      {
        "code": "4",
        "label": "Ziemlich"
      },
      {
        "code": "5",
        "label": "Sehr"
      }
    ],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "",
    "matrix_group_name": "communication_platform",
    "matrix_ranking": "",
    "field_annotation": "",
    "evaluated_logic": ""
  },
  {
    "field_name": "DISCUTHREAT",
    "form_name": "communication_platform",
    "section_header": "Wish to discuss treatment",
    "field_type": "radio",
    "field_label": "Wünschen Sie sich einen Termin, um über ihre Diabetestherapie zu sprechen?",
    "select_choices_or_calculations": [
      {
        "code": "1",
        "label": "Ja"
      },
      {
        "code": "0",
        "label": "Nein"
      }
    ],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "",
    "matrix_group_name": "communication_platform",
    "matrix_ranking": "",
    "field_annotation": "",
    "evaluated_logic": ""
  },
  {
    "field_name": "SUPPTHREAT",
    "form_name": "communication_platform",
    "section_header": "Wish für support with treatment",
    "field_type": "radio",
    "field_label": "Wünschen Sie sich mehr Unterstützung bei Ihrer Diabetestherapie?",
    "select_choices_or_calculations": [
      {
        "code": "1",
        "label": "Ja"
      },
      {
        "code": "0",
        "label": "Nein"
      }
    ],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "",
    "matrix_group_name": "communication_platform",
    "matrix_ranking": "",
    "field_annotation": "",
    "evaluated_logic": ""
  }
]
