=== RADAR-base/RADAR-REDCap-aRMT-Definitions/docs/definition-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "title": "RADAR-base definition schema for the aRMT app questionnaires",
  "description": "A definition file for the RADAR-base aRMT app describes what questions and question input types should be displayed to the user for a questionnaire. This contains an array of questions.",
  "items": {
    "type": "object",
    "description": "A single question describing the display text, question input type, and other relevant information.",
    "properties": {
      "field_name": {
        "type": "string"
      },
      "form_name": {
        "type": "string"
      },
      "section_header": {
        "type": "string"
      },
      "field_type": {
        "type": "string",
        "enum": [
          "radio",
          "checkbox",
          "healthkit",
          "range",
          "range-info",
          "slider",
          "slider-vertical",
          "info",
          "audio",
          "guided-audio",
          "timed",
          "text",
          "yesno",
          "descriptive",
          "matrix-radio",
          "launcher",
          "web",
          "notes"
        ]
      },
      "field_label": {
        "type": "string"
      },
      "select_choices_or_calculations": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string"
                },
                "label": {
                  "type": "string"
                }
              },
              "required": [
                "code",
                "label"
              ]
            }
          }
        ]
      },
      "field_note": {
        "type": "string"
      },
      "text_validation_type_or_show_slider_number": {
        "anyOf": [
          {
            "type": "string",
            "enum": [
              "date",
              "time",
              "duration",
              "date_dmy",
              "datetime_dmy",
              "number",
              "integer"
            ]
          },
          {
            "type": "string",
            "maxLength": 0
          }
        ]
      },
      "text_validation_min": {
        "type": "string"
      },
      "text_validation_max": {
        "type": "string"
      },
      "identifier": {
        "type": "string"
      },
      "branching_logic": {
        "type": "string"
      },
      "required_field": {
        "type": "string"
      },
      "custom_alignment": {
        "type": "string"
      },
      "question_number": {
        "type": "string"
      },
      "matrix_group_name": {
        "type": "string"
      },
      "matrix_ranking": {
        "type": "string"
      },
      "field_annotation": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "object"
          }
        ]
      },
      "evaluated_logic": {
        "type": "string"
      }
    },
    "required": [
      "field_name",
      "form_name",
      "section_header",
      "field_type",
      "select_choices_or_calculations",
      "field_note",
      "text_validation_type_or_show_slider_number",
      "text_validation_min",
      "text_validation_max",
      "identifier",
      "branching_logic",
      "required_field",
      "custom_alignment",
      "question_number",
      "matrix_group_name",
      "matrix_ranking",
      "field_annotation",
      "evaluated_logic"
    ]
  }
}

=== RADAR-base/RADAR-REDCap-aRMT-Definitions/questionnaires/weight_and_waist_circumference/weight_and_waist_circumference_armt_es.json
[
    {
        "field_name": "weight_instructions",
        "form_name": "weight_and_waist_circumference",
        "section_header": "",
        "field_type": "descriptive",
        "field_label": "Usando la balanza del estudio, díganos su peso",
        "select_choices_or_calculations": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "weight_unit",
        "form_name": "weight_and_waist_circumference",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Por favor, seleccione la unidad",
        "select_choices_or_calculations": [
            {
                "code": "kg",
                "label": "kilogramos (kg)"
            },
            {
                "code": "stlb",
                "label": "stone (st) y libras (lb)"
            },
            {
                "code": "lb",
                "label": "libras (lb)"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "y",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "weightkg_measure",
        "form_name": "weight_and_waist_circumference",
        "section_header": "",
        "field_type": "text",
        "field_label": "Peso en kilogramos(kg)",
        "select_choices_or_calculations": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[weight_unit] = 'kg'",
        "required_field": "y",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": "responses['weight_unit'] ==  'kg'"
    },
    {
        "field_name": "weightstlb_measure",
        "form_name": "weight_and_waist_circumference",
        "section_header": "",
        "field_type": "text",
        "field_label": "Peso en libras (lb)",
        "select_choices_or_calculations": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[weight_unit] = 'stlb'",
        "required_field": "y",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": "responses['weight_unit'] ==  'stlb'"
    },
    {
        "field_name": "weightlb_measure",
        "form_name": "weight_and_waist_circumference",
        "section_header": "",
        "field_type": "text",
        "field_label": "Peso en libras (lb)",
        "select_choices_or_calculations": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[weight_unit] = 'lb'",
        "required_field": "y",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": "responses['weight_unit'] ==  'lb'"
    },
    {
        "field_name": "waist_instructions",
        "form_name": "weight_and_waist_circumference",
        "section_header": "",
        "field_type": "info",
        "field_label": "",
        "select_choices_or_calculations": [
            {
                "code": "Part1",
                "label": "¿Cómo medir la cintura?"
            },
            {
                "code": "Part2",
                "label": "Encuentra la parte inferior de tus costillas y la parte superior de tus caderas."
            },
            {
                "code": "Part3",
                "label": "Coloca una cinta métrica alrededor de tu cintura en un punto a medio camino entre ellas (justo por encima del ombligo)."
            },
            {
                "code": "Part4",
                "label": "Asegúrate de que esté bien tensada, pero que no se clave en tu piel."
            },
            {
                "code": "Part5",
                "label": "Exhala con naturalidad y toma la medida."
            },
            {
                "code": "Part6",
                "label": "Vuelve a tomarte la medida, para estar seguro."
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "info-type",
        "evaluated_logic": ""
    },
    {
        "field_name": "waist_unit",
        "form_name": "weight_and_waist_circumference",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Por favor, seleccione la unidad",
        "select_choices_or_calculations": [
            {
                "code": "cm",
                "label": "cm"
            },
            {
                "code": "inches",
                "label": "pulgadas"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "y",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "waistcm_measure",
        "form_name": "weight_and_waist_circumference",
        "section_header": "",
        "field_type": "text",
        "field_label": "Cintura en cm",
        "select_choices_or_calculations": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[waist_unit] = 'cm'",
        "required_field": "y",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": "responses['waist_unit'] ==  'cm'"
    },
    {
        "field_name": "waistinches_measure",
        "form_name": "weight_and_waist_circumference",
        "section_header": "",
        "field_type": "text",
        "field_label": "Cintura en pulgadas",
        "select_choices_or_calculations": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[waist_unit] = 'inches'",
        "required_field": "y",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": "responses['waist_unit'] ==  'inches'"
    }
]

=== RADAR-base/RADAR-REDCap-aRMT-Definitions/questionnaires/ers/ers_armt.json
[
    {
        "field_name": "do_you_feel_your_state_has",
        "form_name": "ers",
        "section_header": "",
        "field_type": "range",
        "field_label": "How have your COPD symptoms changed in recent days?",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "0 Worsened"
            },
            {
                "code": "1",
                "label": "1"
            },
            {
                "code": "2",
                "label": "2"
            },
            {
                "code": "3",
                "label": "3 No change"
            },
            {
                "code": "4",
                "label": "4"
            },
            {
                "code": "5",
                "label": "5"
            },
            {
                "code": "6",
                "label": "6 Improved"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "y",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "range-type",
        "evaluated_logic": ""
    },
    {
        "field_name": "how_likely_do_you_feel_it",
        "form_name": "ers",
        "section_header": "",
        "field_type": "range",
        "field_label": "How likely do you feel it is that you have a chest infection / acute exacerbations based on increasing symptoms and/ or sputum production?",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "None"
            },
            {
                "code": "1",
                "label": "1"
            },
            {
                "code": "2",
                "label": "2"
            },
            {
                "code": "3",
                "label": "3"
            },
            {
                "code": "4",
                "label": "4"
            },
            {
                "code": "5",
                "label": "Very Likely"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[do_you_feel_your_state_has] = 0 or [do_you_feel_your_state_has] = 1 or [do_you_feel_your_state_has] = 2 or [do_you_feel_your_state_has] = 3 or [do_you_feel_your_state_has] = 4 or [do_you_feel_your_state_has] = 5",
        "required_field": "y",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "range-type",
        "evaluated_logic": "responses['do_you_feel_your_state_has'] ==  0 || responses['do_you_feel_your_state_has'] ==  1 || responses['do_you_feel_your_state_has'] ==  2 || responses['do_you_feel_your_state_has'] ==  3 || responses['do_you_feel_your_state_has'] ==  4 || responses['do_you_feel_your_state_has'] ==  5"
    },
    {
        "field_name": "please_select_the_ones_tha",
        "form_name": "ers",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "Are you taking any medications for exacerbation today? Please select all the ones that apply:",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "None"
            },
            {
                "code": "1",
                "label": "Steroids"
            },
            {
                "code": "2",
                "label": "Antibiotics"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    }
]

=== RADAR-base/RADAR-REDCap-aRMT-Definitions/questionnaires/recurrent_picture_naming/recurrent_picture_naming_armt.json
[
  {
    "field_name": "pn_prep_1",
    "form_name": "picture_naming",
    "section_header": "Picture Naming Task",
    "field_type": "info",
    "field_label": "In this task you will be shown a picture of an object. Please say the name of the object out loud.",
    "select_choices_or_calculations": [
      {
        "code": "Instructions",
        "label": "Look at each picture and say what it is as quickly as you can. You will have up to 15 seconds for each item."
      },
      {
        "code": "Format",
        "label": "There are 6 pictures in total, shown one at a time. The instruction will be read aloud when each picture appears."
      },
      {
        "code": "Note",
        "label": "If you are unable to speak right now, you will have the option to indicate this on each screen."
      }
    ],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "",
    "matrix_group_name": "pn",
    "matrix_ranking": "",
    "field_annotation": "",
    "evaluated_logic": ""
  },
  {
    "field_name": "pn_prep_2",
    "form_name": "picture_naming",
    "section_header": "Ready to begin",
    "field_type": "info",
    "field_label": "",
    "select_choices_or_calculations": [
      {
        "code": "Important",
        "label": "From the next screen onwards you will not be able to go back. Make sure you are in a quiet place and are ready to respond. Press Next to begin."
      }
    ],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "",
    "matrix_group_name": "pn",
    "matrix_ranking": "",
    "field_annotation": "",
    "evaluated_logic": ""
  },
  {
    "field_name": "pn_item_1",
    "form_name": "picture_naming",
    "section_header": "Picture 1 of 6",
    "field_type": "guided-audio",
    "field_label": "What is this?",
    "select_choices_or_calculations": [],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "1",
    "matrix_group_name": "pn",
    "matrix_ranking": "",
    "field_annotation": {
      "auto_tts": true,
      "auto_record_after_tts": true,
      "record_seconds": 15,
      "allow_replay_prompt": false,
      "unable_to_speak_option": true,
      "image": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/f04834f6c1f7d21cbac90653650129b337450eb6/questionnaires/recurrent_picture_naming/dog.png"
    },
    "evaluated_logic": ""
  },
  {
    "field_name": "pn_item_2",
    "form_name": "picture_naming",
    "section_header": "Picture 2 of 6",
    "field_type": "guided-audio",
    "field_label": "What is this?",
    "select_choices_or_calculations": [],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "2",
    "matrix_group_name": "pn",
    "matrix_ranking": "",
    "field_annotation": {
      "auto_tts": true,
      "auto_record_after_tts": true,
      "record_seconds": 15,
      "allow_replay_prompt": false,
      "unable_to_speak_option": true,
      "image": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/f04834f6c1f7d21cbac90653650129b337450eb6/questionnaires/recurrent_picture_naming/escalator.png"
    },
    "evaluated_logic": ""
  },
  {
    "field_name": "pn_item_3",
    "form_name": "picture_naming",
    "section_header": "Picture 3 of 6",
    "field_type": "guided-audio",
    "field_label": "What is this?",
    "select_choices_or_calculations": [],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "3",
    "matrix_group_name": "pn",
    "matrix_ranking": "",
    "field_annotation": {
      "auto_tts": true,
      "auto_record_after_tts": true,
      "record_seconds": 15,
      "allow_replay_prompt": false,
      "unable_to_speak_option": true,
      "image": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/f04834f6c1f7d21cbac90653650129b337450eb6/questionnaires/recurrent_picture_naming/pencil.png"
    },
    "evaluated_logic": ""
  },
  {
    "field_name": "pn_item_4",
    "form_name": "picture_naming",
    "section_header": "Picture 4 of 6",
    "field_type": "guided-audio",
    "field_label": "What is this?",
    "select_choices_or_calculations": [],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "4",
    "matrix_group_name": "pn",
    "matrix_ranking": "",
    "field_annotation": {
      "auto_tts": true,
      "auto_record_after_tts": true,
      "record_seconds": 15,
      "allow_replay_prompt": false,
      "unable_to_speak_option": true,
      "image": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/f04834f6c1f7d21cbac90653650129b337450eb6/questionnaires/recurrent_picture_naming/octopus.png"
    },
    "evaluated_logic": ""
  },
  {
    "field_name": "pn_item_5",
    "form_name": "picture_naming",
    "section_header": "Picture 5 of 6",
    "field_type": "guided-audio",
    "field_label": "What is this?",
    "select_choices_or_calculations": [],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "5",
    "matrix_group_name": "pn",
    "matrix_ranking": "",
    "field_annotation": {
      "auto_tts": true,
      "auto_record_after_tts": true,
      "record_seconds": 15,
      "allow_replay_prompt": false,
      "unable_to_speak_option": true,
      "image": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/f04834f6c1f7d21cbac90653650129b337450eb6/questionnaires/recurrent_picture_naming/wheelchair.png"
    },
    "evaluated_logic": ""
  },
  {
    "field_name": "pn_item_6",
    "form_name": "picture_naming",
    "section_header": "Picture 6 of 6",
    "field_type": "guided-audio",
    "field_label": "What is this?",
    "select_choices_or_calculations": [],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "6",
    "matrix_group_name": "pn",
    "matrix_ranking": "",
    "field_annotation": {
      "auto_tts": true,
      "auto_record_after_tts": true,
      "record_seconds": 15,
      "allow_replay_prompt": false,
      "unable_to_speak_option": true,
      "image": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/f04834f6c1f7d21cbac90653650129b337450eb6/questionnaires/recurrent_picture_naming/hammock.png"
    },
    "evaluated_logic": ""
  }
]
